version: '3.8'
services:
  postgres:
    image: thaliab/postgres-source:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"
